# @tag apache - setup the apache web server
# @tag ssl - setup SSL certificates and configuration
# @tag apache-mod-evasive - setup apache anti-DoS module

galaxy_info:
  role_name: softing_linux_timezone
  author: "Illia Skorik <ilya.skorik@gmail.com>"
  description: "Different roles for atomically configuring a linux host"
  license: "GPL-3.0"
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "10"
        - "11"
  galaxy_tags:
    - linux
